Add missing <climits> header for INT_MAX constant
The patch adds a missing <climits> header needed for `INT_MAX` constant.

    MixFit.cc: In function 'void makeFullFitVariables()':
    MixFit.cc:905:48: error: 'INT_MAX' was not declared in this scope

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>